migrate(
  (app) => {
    const collection = app.findCollectionByNameOrId('hsp_data')

    const seedData = [
      {
        state: 'PR',
        city: 'Curitiba',
        annual: 4.81,
        jan: 5.12,
        feb: 4.95,
        mar: 4.6,
        apr: 4.05,
        may: 3.65,
        jun: 3.3,
        jul: 3.55,
        aug: 4.2,
        sep: 4.65,
        oct: 5.1,
        nov: 5.35,
        dec: 5.4,
      },
      {
        state: 'PR',
        city: 'Londrina',
        annual: 5.2,
        jan: 5.4,
        feb: 5.35,
        mar: 5.1,
        apr: 4.7,
        may: 4.3,
        jun: 4.0,
        jul: 4.25,
        aug: 4.8,
        sep: 5.2,
        oct: 5.5,
        nov: 5.65,
        dec: 5.7,
      },
      {
        state: 'PR',
        city: 'Maringa',
        annual: 5.1,
        jan: 5.3,
        feb: 5.25,
        mar: 5.0,
        apr: 4.6,
        may: 4.2,
        jun: 3.9,
        jul: 4.15,
        aug: 4.7,
        sep: 5.1,
        oct: 5.4,
        nov: 5.55,
        dec: 5.6,
      },
      {
        state: 'PR',
        city: 'Ponta Grossa',
        annual: 4.9,
        jan: 5.15,
        feb: 5.0,
        mar: 4.7,
        apr: 4.15,
        may: 3.75,
        jun: 3.4,
        jul: 3.65,
        aug: 4.3,
        sep: 4.75,
        oct: 5.2,
        nov: 5.45,
        dec: 5.5,
      },
      {
        state: 'PR',
        city: 'Cascavel',
        annual: 5.3,
        jan: 5.5,
        feb: 5.45,
        mar: 5.2,
        apr: 4.8,
        may: 4.4,
        jun: 4.1,
        jul: 4.35,
        aug: 4.9,
        sep: 5.3,
        oct: 5.6,
        nov: 5.75,
        dec: 5.8,
      },
      {
        state: 'SP',
        city: 'Sao Paulo',
        annual: 4.9,
        jan: 5.1,
        feb: 5.05,
        mar: 4.75,
        apr: 4.2,
        may: 3.8,
        jun: 3.5,
        jul: 3.75,
        aug: 4.4,
        sep: 4.85,
        oct: 5.2,
        nov: 5.35,
        dec: 5.4,
      },
      {
        state: 'SP',
        city: 'Campinas',
        annual: 5.1,
        jan: 5.3,
        feb: 5.25,
        mar: 4.95,
        apr: 4.4,
        may: 4.0,
        jun: 3.7,
        jul: 3.95,
        aug: 4.6,
        sep: 5.05,
        oct: 5.4,
        nov: 5.55,
        dec: 5.6,
      },
      {
        state: 'SP',
        city: 'Santos',
        annual: 4.7,
        jan: 5.05,
        feb: 5.1,
        mar: 4.8,
        apr: 4.2,
        may: 3.75,
        jun: 3.45,
        jul: 3.7,
        aug: 4.25,
        sep: 4.6,
        oct: 4.9,
        nov: 5.0,
        dec: 5.1,
      },
      {
        state: 'SP',
        city: 'Ribeirao Preto',
        annual: 5.4,
        jan: 5.55,
        feb: 5.5,
        mar: 5.25,
        apr: 4.75,
        may: 4.35,
        jun: 4.05,
        jul: 4.3,
        aug: 4.95,
        sep: 5.4,
        oct: 5.7,
        nov: 5.8,
        dec: 5.85,
      },
      {
        state: 'RJ',
        city: 'Rio de Janeiro',
        annual: 4.7,
        jan: 5.15,
        feb: 5.3,
        mar: 4.95,
        apr: 4.35,
        may: 3.85,
        jun: 3.55,
        jul: 3.75,
        aug: 4.3,
        sep: 4.6,
        oct: 4.8,
        nov: 4.9,
        dec: 5.1,
      },
      {
        state: 'RJ',
        city: 'Niteroi',
        annual: 4.65,
        jan: 5.1,
        feb: 5.25,
        mar: 4.9,
        apr: 4.3,
        may: 3.8,
        jun: 3.5,
        jul: 3.7,
        aug: 4.25,
        sep: 4.55,
        oct: 4.75,
        nov: 4.85,
        dec: 5.05,
      },
      {
        state: 'MG',
        city: 'Belo Horizonte',
        annual: 5.3,
        jan: 5.45,
        feb: 5.4,
        mar: 5.15,
        apr: 4.65,
        may: 4.25,
        jun: 3.95,
        jul: 4.2,
        aug: 4.85,
        sep: 5.3,
        oct: 5.6,
        nov: 5.7,
        dec: 5.75,
      },
      {
        state: 'MG',
        city: 'Uberlandia',
        annual: 5.5,
        jan: 5.6,
        feb: 5.55,
        mar: 5.35,
        apr: 4.9,
        may: 4.5,
        jun: 4.2,
        jul: 4.45,
        aug: 5.1,
        sep: 5.5,
        oct: 5.75,
        nov: 5.85,
        dec: 5.9,
      },
      {
        state: 'RS',
        city: 'Porto Alegre',
        annual: 4.6,
        jan: 5.2,
        feb: 4.9,
        mar: 4.45,
        apr: 3.85,
        may: 3.3,
        jun: 2.95,
        jul: 3.15,
        aug: 3.85,
        sep: 4.4,
        oct: 4.95,
        nov: 5.35,
        dec: 5.55,
      },
      {
        state: 'RS',
        city: 'Caxias do Sul',
        annual: 4.4,
        jan: 5.0,
        feb: 4.7,
        mar: 4.25,
        apr: 3.65,
        may: 3.1,
        jun: 2.75,
        jul: 2.95,
        aug: 3.65,
        sep: 4.2,
        oct: 4.75,
        nov: 5.15,
        dec: 5.35,
      },
      {
        state: 'SC',
        city: 'Florianopolis',
        annual: 4.5,
        jan: 5.05,
        feb: 4.85,
        mar: 4.45,
        apr: 3.9,
        may: 3.35,
        jun: 3.05,
        jul: 3.25,
        aug: 3.9,
        sep: 4.35,
        oct: 4.8,
        nov: 5.15,
        dec: 5.35,
      },
      {
        state: 'SC',
        city: 'Joinville',
        annual: 4.4,
        jan: 4.95,
        feb: 4.75,
        mar: 4.35,
        apr: 3.8,
        may: 3.25,
        jun: 2.95,
        jul: 3.15,
        aug: 3.8,
        sep: 4.25,
        oct: 4.7,
        nov: 5.05,
        dec: 5.25,
      },
      {
        state: 'SC',
        city: 'Chapeco',
        annual: 4.3,
        jan: 4.9,
        feb: 4.65,
        mar: 4.2,
        apr: 3.6,
        may: 3.05,
        jun: 2.7,
        jul: 2.9,
        aug: 3.6,
        sep: 4.15,
        oct: 4.65,
        nov: 5.0,
        dec: 5.2,
      },
      {
        state: 'GO',
        city: 'Goiania',
        annual: 5.6,
        jan: 5.55,
        feb: 5.55,
        mar: 5.45,
        apr: 5.1,
        may: 4.75,
        jun: 4.45,
        jul: 4.75,
        aug: 5.4,
        sep: 5.75,
        oct: 5.9,
        nov: 5.9,
        dec: 5.85,
      },
      {
        state: 'MT',
        city: 'Cuiaba',
        annual: 5.8,
        jan: 5.55,
        feb: 5.65,
        mar: 5.7,
        apr: 5.55,
        may: 5.25,
        jun: 5.05,
        jul: 5.35,
        aug: 6.05,
        sep: 6.3,
        oct: 6.35,
        nov: 6.05,
        dec: 5.8,
      },
      {
        state: 'MS',
        city: 'Campo Grande',
        annual: 5.5,
        jan: 5.5,
        feb: 5.5,
        mar: 5.4,
        apr: 5.0,
        may: 4.6,
        jun: 4.3,
        jul: 4.6,
        aug: 5.25,
        sep: 5.65,
        oct: 5.85,
        nov: 5.85,
        dec: 5.8,
      },
      {
        state: 'BA',
        city: 'Salvador',
        annual: 5.4,
        jan: 5.75,
        feb: 5.85,
        mar: 5.65,
        apr: 5.1,
        may: 4.65,
        jun: 4.45,
        jul: 4.55,
        aug: 5.05,
        sep: 5.4,
        oct: 5.55,
        nov: 5.65,
        dec: 5.75,
      },
      {
        state: 'PE',
        city: 'Recife',
        annual: 5.6,
        jan: 5.95,
        feb: 6.05,
        mar: 5.8,
        apr: 5.25,
        may: 4.8,
        jun: 4.55,
        jul: 4.6,
        aug: 5.2,
        sep: 5.65,
        oct: 5.9,
        nov: 6.0,
        dec: 6.1,
      },
      {
        state: 'CE',
        city: 'Fortaleza',
        annual: 5.7,
        jan: 5.85,
        feb: 5.8,
        mar: 5.6,
        apr: 5.3,
        may: 5.05,
        jun: 4.95,
        jul: 5.2,
        aug: 5.95,
        sep: 6.4,
        oct: 6.45,
        nov: 6.2,
        dec: 5.9,
      },
    ]

    for (const sd of seedData) {
      try {
        app.findFirstRecordByData('hsp_data', 'city', sd.city)
      } catch (_) {
        const record = new Record(collection)
        record.set('state', sd.state)
        record.set('city', sd.city)
        record.set('annual', sd.annual)
        record.set('jan', sd.jan)
        record.set('feb', sd.feb)
        record.set('mar', sd.mar)
        record.set('apr', sd.apr)
        record.set('may', sd.may)
        record.set('jun', sd.jun)
        record.set('jul', sd.jul)
        record.set('aug', sd.aug)
        record.set('sep', sd.sep)
        record.set('oct', sd.oct)
        record.set('nov', sd.nov)
        record.set('dec', sd.dec)
        app.save(record)
      }
    }
  },
  (app) => {
    try {
      const col = app.findCollectionByNameOrId('hsp_data')
      app.truncateCollection(col)
    } catch (_) {}
  },
)
